window.translationMap = {"My Account":null,"Stay signed in":null,"Login":null,"Registration":null,"Sign into your account":null,"Forgot Password":null,"Password":null,"E-mail":null,"My Orders":null,"Pages":null,"Close":null,"Upload":null,"Please fill out the evaluation form first":null,"Please rate the quality of paper you received":null,"Very poor":null,"Average":null,"Good":null,"Perfect":null,"Fair":null,"Almost good":null,"Excellent":null,"Not that bad":null,"Poor":null,"Very good":null,"Ok":null,"1 Very poor":null,"words":null,"Clear request":null,"Please select the deadline first":null,"Save & reserve money":null,"Hide description":null,"Read about featured orders":null,"Cancel":null,"now":null,"Approve & Release Final Payment":null,"Delete":null,"information":null,"Save deadline":null,"Information":null,"This bid has been rejected by writer.":null,"This bid has been changed by writer.":null,"Please fill the form first":null,"This field is required":null,"Incorrect e-mail":null,"Log Out":null,"Logout":null,"Save changes":null,"Please, choose file":null,"Incorrect password.":null,"Your E-mail":null,"Your e-mail":null,"Select type of paper":null,"Writer has award":null,"Writer's avatar":null,"completed orders":null,"pages":null,"Show writer's comment":null,"Writer's feedback":null,"Customer's feedback":null,"Writer\u2019s rating":null,"Request this writer":null,"Orders finished":null,"Orders in progress":null,"Create new order and request this writer to completed it":null,"Information about writer":null,"Orders canceled by customers":null,"Writer's orders":null,"Orders canceled by this writer":null,"Last awarded":null,"Awards":null,"Writer\u2019s comment":null,"The writer is not cooperating with our company at the moment.":null,"Customer\u2019s feedback":null,"Orders completed in disciplines":null,"There are no available writers":null,"Try changing the number of completed orders or the discipline.":null,"Hidden by customer":null,"Error. Incorrect email or email already exist in our DB.":null,"The Password field must contain at least 7 chatacters":null,"The Password field is required.":null,"The Password confirmation field is required":null,"The passwords do not match. Please reenter.":null,"Writer":null,"estimation":null,"hieroglyphs":null}; window.translationLanguage = "en";window['__'] = function (source){
	if (typeof window.translationMap !== 'undefined'){
		if (window.translationMap[source]){
			return window.translationMap[source];
		} 
		else if (window.translationLanguage !== 'en' && window.translationMap[source] !== null){
			jQuery.post('/bricks/js_translation.html', {message: source});
		}
	}
	return source;
};
